name: CombatLog
version: '${project.version}'
main: org.hg.combatlog.CombatLog
api-version: 1.18
description: Filabdict
commands:
  combat:
    description: Получить лог урона
    permission: combat_log
  combat_page:
    description: Перелестнуть на страницу